"""add_load_in_and_sound_check_times_to_band_events

Revision ID: 028f0009ad52
Revises: add04c72069c
Create Date: 2025-12-27 00:56:34.287781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '028f0009ad52'
down_revision: Union[str, Sequence[str], None] = 'add04c72069c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('band_events', sa.Column('load_in_time', sa.Time(), nullable=True))
    op.add_column('band_events', sa.Column('sound_check_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('band_events', 'sound_check_time')
    op.drop_column('band_events', 'load_in_time')
    # ### end Alembic commands ###
