"""Fix ticket_number uniqueness constraint to be per-allocation

Revision ID: 45577f9889d9
Revises: 95074e84ea73
Create Date: 2026-01-11 13:04:43.946997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45577f9889d9'
down_revision: Union[str, Sequence[str], None] = '95074e84ea73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_physical_ticket_sales_ticket_number'), table_name='physical_ticket_sales')
    op.create_index(op.f('ix_physical_ticket_sales_ticket_number'), 'physical_ticket_sales', ['ticket_number'], unique=False)
    op.create_unique_constraint('uq_allocation_ticket_number', 'physical_ticket_sales', ['allocation_id', 'ticket_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_allocation_ticket_number', 'physical_ticket_sales', type_='unique')
    op.drop_index(op.f('ix_physical_ticket_sales_ticket_number'), table_name='physical_ticket_sales')
    op.create_index(op.f('ix_physical_ticket_sales_ticket_number'), 'physical_ticket_sales', ['ticket_number'], unique=True)
    # ### end Alembic commands ###
