"""add_venue_contact_fields

Revision ID: 51482139bf31
Revises: dc09917694dd
Create Date: 2025-12-21 16:31:59.192436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51482139bf31'
down_revision: Union[str, Sequence[str], None] = 'dc09917694dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('contact_name', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('contact_email', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('contact_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'contact_phone')
    op.drop_column('venues', 'contact_email')
    op.drop_column('venues', 'contact_name')
    # ### end Alembic commands ###
