"""add_city_and_state_to_bands

Revision ID: 5c556309ae6f
Revises: 89ac9bedec4e
Create Date: 2025-01-15 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c556309ae6f'
down_revision: Union[str, Sequence[str], None] = '89ac9bedec4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bands', sa.Column('city', sa.String(), nullable=True))
    op.add_column('bands', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bands', 'state')
    op.drop_column('bands', 'city')
    # ### end Alembic commands ###

