"""Add social media fields to bands

Revision ID: 60202d8bf25d
Revises: 21baaf6ce640
Create Date: 2025-12-25 00:44:09.527199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60202d8bf25d'
down_revision: Union[str, Sequence[str], None] = '21baaf6ce640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bands', sa.Column('instagram_url', sa.String(), nullable=True))
    op.add_column('bands', sa.Column('facebook_url', sa.String(), nullable=True))
    op.add_column('bands', sa.Column('spotify_url', sa.String(), nullable=True))
    op.add_column('bands', sa.Column('website_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bands', 'website_url')
    op.drop_column('bands', 'spotify_url')
    op.drop_column('bands', 'facebook_url')
    op.drop_column('bands', 'instagram_url')
    # ### end Alembic commands ###
