"""Add support for band created events

Revision ID: 831d2e150938
Revises: 5c556309ae6f
Create Date: 2026-01-07 22:39:20.662595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '831d2e150938'
down_revision: Union[str, Sequence[str], None] = '5c556309ae6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gig_engagements_band_id'), table_name='gig_engagements')
    op.drop_index(op.f('ix_gig_engagements_created_at'), table_name='gig_engagements')
    op.drop_index(op.f('ix_gig_engagements_engagement_type'), table_name='gig_engagements')
    op.drop_index(op.f('ix_gig_engagements_event_id'), table_name='gig_engagements')
    op.drop_index(op.f('ix_gig_engagements_id'), table_name='gig_engagements')
    op.drop_index(op.f('ix_gig_engagements_session_id'), table_name='gig_engagements')
    op.drop_index(op.f('ix_gig_engagements_user_id'), table_name='gig_engagements')
    op.drop_table('gig_engagements')
    op.add_column('events', sa.Column('created_by_band_id', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('location_name', sa.String(), nullable=True))
    op.add_column('events', sa.Column('street_address', sa.String(), nullable=True))
    op.add_column('events', sa.Column('city', sa.String(), nullable=True))
    op.add_column('events', sa.Column('state', sa.String(), nullable=True))
    op.add_column('events', sa.Column('zip_code', sa.String(), nullable=True))
    op.alter_column('events', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_events_created_by_band_id'), 'events', ['created_by_band_id'], unique=False)
    op.create_foreign_key(None, 'events', 'bands', ['created_by_band_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_created_by_band_id'), table_name='events')
    op.alter_column('events', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('events', 'zip_code')
    op.drop_column('events', 'state')
    op.drop_column('events', 'city')
    op.drop_column('events', 'street_address')
    op.drop_column('events', 'location_name')
    op.drop_column('events', 'created_by_band_id')
    op.create_table('gig_engagements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('band_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engagement_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('duration_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('list_position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('search_query', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('filters_applied', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommendation_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('device_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], name=op.f('gig_engagements_band_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('gig_engagements_event_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('gig_engagements_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('gig_engagements_pkey'))
    )
    op.create_index(op.f('ix_gig_engagements_user_id'), 'gig_engagements', ['user_id'], unique=False)
    op.create_index(op.f('ix_gig_engagements_session_id'), 'gig_engagements', ['session_id'], unique=False)
    op.create_index(op.f('ix_gig_engagements_id'), 'gig_engagements', ['id'], unique=False)
    op.create_index(op.f('ix_gig_engagements_event_id'), 'gig_engagements', ['event_id'], unique=False)
    op.create_index(op.f('ix_gig_engagements_engagement_type'), 'gig_engagements', ['engagement_type'], unique=False)
    op.create_index(op.f('ix_gig_engagements_created_at'), 'gig_engagements', ['created_at'], unique=False)
    op.create_index(op.f('ix_gig_engagements_band_id'), 'gig_engagements', ['band_id'], unique=False)
    # ### end Alembic commands ###
