"""add_recurring_event_fields

Revision ID: 8e7d91915a1d
Revises: 028f0009ad52
Create Date: 2025-12-28 20:44:06.578687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e7d91915a1d'
down_revision: Union[str, Sequence[str], None] = '028f0009ad52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_recurring as nullable first, set default, then make it NOT NULL
    op.add_column('events', sa.Column('is_recurring', sa.Boolean(), nullable=True, server_default='false'))
    op.execute("UPDATE events SET is_recurring = false WHERE is_recurring IS NULL")
    op.alter_column('events', 'is_recurring', nullable=False, server_default='false')
    
    op.add_column('events', sa.Column('recurring_day_of_week', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('recurring_frequency', sa.String(), nullable=True))
    op.add_column('events', sa.Column('recurring_start_date', sa.Date(), nullable=True))
    op.add_column('events', sa.Column('recurring_end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'recurring_end_date')
    op.drop_column('events', 'recurring_start_date')
    op.drop_column('events', 'recurring_frequency')
    op.drop_column('events', 'recurring_day_of_week')
    op.drop_column('events', 'is_recurring')
    # ### end Alembic commands ###
