"""add_eventapplication_fields

Revision ID: 936b2b23825b
Revises: 51482139bf31
Create Date: 2025-12-21 17:56:56.016215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '936b2b23825b'
down_revision: Union[str, Sequence[str], None] = '51482139bf31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('events', sa.Column('is_pending', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('accepts_applications', sa.Boolean(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE events SET is_pending = FALSE WHERE is_pending IS NULL")
    op.execute("UPDATE events SET accepts_applications = FALSE WHERE accepts_applications IS NULL")
    
    # Now make the columns NOT NULL
    op.alter_column('events', 'is_pending', nullable=False)
    op.alter_column('events', 'accepts_applications', nullable=False)
    
    op.create_index(op.f('ix_events_accepts_applications'), 'events', ['accepts_applications'], unique=False)
    op.create_index(op.f('ix_events_is_pending'), 'events', ['is_pending'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_is_pending'), table_name='events')
    op.drop_index(op.f('ix_events_accepts_applications'), table_name='events')
    op.drop_column('events', 'accepts_applications')
    op.drop_column('events', 'is_pending')
    # ### end Alembic commands ###
