"""add_eventapplication_fields

Revision ID: b1e807518aa4
Revises: 936b2b23825b
Create Date: 2025-12-21 18:04:10.211409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e807518aa4'
down_revision: Union[str, Sequence[str], None] = '936b2b23825b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('events', sa.Column('status', sa.String(), nullable=True))
    op.add_column('events', sa.Column('is_open_for_applications', sa.Boolean(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE events SET status = 'confirmed' WHERE status IS NULL")
    op.execute("UPDATE events SET is_open_for_applications = FALSE WHERE is_open_for_applications IS NULL")
    
    # Now make the columns NOT NULL
    op.alter_column('events', 'status', nullable=False)
    op.alter_column('events', 'is_open_for_applications', nullable=False)
    
    # Drop old indexes and columns
    op.drop_index(op.f('ix_events_accepts_applications'), table_name='events')
    op.drop_index(op.f('ix_events_is_pending'), table_name='events')
    
    # Create new index
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    
    # Drop old columns
    op.drop_column('events', 'accepts_applications')
    op.drop_column('events', 'is_pending')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_pending', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('accepts_applications', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.create_index(op.f('ix_events_is_pending'), 'events', ['is_pending'], unique=False)
    op.create_index(op.f('ix_events_accepts_applications'), 'events', ['accepts_applications'], unique=False)
    op.drop_column('events', 'is_open_for_applications')
    op.drop_column('events', 'status')
    # ### end Alembic commands ###
