"""add_image_path_to_bands

Revision ID: dc09917694dd
Revises: b0c8cce6e448
Create Date: 2025-12-20 12:37:11.969116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc09917694dd'
down_revision: Union[str, Sequence[str], None] = 'b0c8cce6e448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bands', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bands', 'image_path')
    # ### end Alembic commands ###
