"""Initial database schema

Revision ID: e0edcfce460b
Revises: 
Create Date: 2025-12-17 14:29:58.499736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0edcfce460b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('invite_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bands_id'), 'bands', ['id'], unique=False)
    op.create_index(op.f('ix_bands_invite_code'), 'bands', ['invite_code'], unique=True)
    op.create_index(op.f('ix_bands_name'), 'bands', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('street_address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('has_sound_provided', sa.Boolean(), nullable=False),
    sa.Column('has_parking', sa.Boolean(), nullable=False),
    sa.Column('age_restriction', sa.Integer(), nullable=True),
    sa.Column('invite_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_city'), 'venues', ['city'], unique=False)
    op.create_index(op.f('ix_venues_id'), 'venues', ['id'], unique=False)
    op.create_index(op.f('ix_venues_invite_code'), 'venues', ['invite_code'], unique=True)
    op.create_index(op.f('ix_venues_name'), 'venues', ['name'], unique=True)
    op.create_table('band_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('band_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('instrument', sa.String(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'band_id', name='unique_user_band')
    )
    op.create_index(op.f('ix_band_members_id'), 'band_members', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('doors_time', sa.Time(), nullable=True),
    sa.Column('show_time', sa.Time(), nullable=False),
    sa.Column('is_ticketed', sa.Boolean(), nullable=False),
    sa.Column('ticket_price', sa.Integer(), nullable=True),
    sa.Column('is_age_restricted', sa.Boolean(), nullable=False),
    sa.Column('age_restriction', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_date'), 'events', ['event_date'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_venue_id'), 'events', ['venue_id'], unique=False)
    op.create_table('venue_availabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'date', name='unique_venue_date_availability')
    )
    op.create_index(op.f('ix_venue_availabilities_date'), 'venue_availabilities', ['date'], unique=False)
    op.create_index(op.f('ix_venue_availabilities_id'), 'venue_availabilities', ['id'], unique=False)
    op.create_index(op.f('ix_venue_availabilities_venue_id'), 'venue_availabilities', ['venue_id'], unique=False)
    op.create_table('venue_operating_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'day_of_week', name='unique_venue_day_of_week')
    )
    op.create_index(op.f('ix_venue_operating_hours_day_of_week'), 'venue_operating_hours', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_venue_operating_hours_id'), 'venue_operating_hours', ['id'], unique=False)
    op.create_index(op.f('ix_venue_operating_hours_venue_id'), 'venue_operating_hours', ['venue_id'], unique=False)
    op.create_table('venue_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'venue_id', name='unique_user_venue')
    )
    op.create_index(op.f('ix_venue_staff_id'), 'venue_staff', ['id'], unique=False)
    op.create_table('band_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('band_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('set_time', sa.Time(), nullable=True),
    sa.Column('set_length_minutes', sa.Integer(), nullable=True),
    sa.Column('performance_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('band_id', 'event_id', name='uq_band_event')
    )
    op.create_index(op.f('ix_band_events_band_id'), 'band_events', ['band_id'], unique=False)
    op.create_index(op.f('ix_band_events_event_id'), 'band_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_band_events_id'), 'band_events', ['id'], unique=False)
    op.create_index(op.f('ix_band_events_status'), 'band_events', ['status'], unique=False)
    op.create_table('band_member_availabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('band_member_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['band_member_id'], ['band_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('band_member_id', 'date', name='unique_member_date_availability')
    )
    op.create_index(op.f('ix_band_member_availabilities_band_member_id'), 'band_member_availabilities', ['band_member_id'], unique=False)
    op.create_index(op.f('ix_band_member_availabilities_date'), 'band_member_availabilities', ['date'], unique=False)
    op.create_index(op.f('ix_band_member_availabilities_id'), 'band_member_availabilities', ['id'], unique=False)
    op.create_table('event_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('band_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('response_note', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'band_id', name='unique_event_band_application')
    )
    op.create_index(op.f('ix_event_applications_applied_at'), 'event_applications', ['applied_at'], unique=False)
    op.create_index(op.f('ix_event_applications_band_id'), 'event_applications', ['band_id'], unique=False)
    op.create_index(op.f('ix_event_applications_event_id'), 'event_applications', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_applications_id'), 'event_applications', ['id'], unique=False)
    op.create_index(op.f('ix_event_applications_status'), 'event_applications', ['status'], unique=False)
    op.create_table('band_availabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('band_id', sa.Integer(), nullable=False),
    sa.Column('band_event_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['band_event_id'], ['band_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('band_id', 'date', name='unique_band_date_availability')
    )
    op.create_index(op.f('ix_band_availabilities_band_event_id'), 'band_availabilities', ['band_event_id'], unique=False)
    op.create_index(op.f('ix_band_availabilities_band_id'), 'band_availabilities', ['band_id'], unique=False)
    op.create_index(op.f('ix_band_availabilities_date'), 'band_availabilities', ['date'], unique=False)
    op.create_index(op.f('ix_band_availabilities_id'), 'band_availabilities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_band_availabilities_id'), table_name='band_availabilities')
    op.drop_index(op.f('ix_band_availabilities_date'), table_name='band_availabilities')
    op.drop_index(op.f('ix_band_availabilities_band_id'), table_name='band_availabilities')
    op.drop_index(op.f('ix_band_availabilities_band_event_id'), table_name='band_availabilities')
    op.drop_table('band_availabilities')
    op.drop_index(op.f('ix_event_applications_status'), table_name='event_applications')
    op.drop_index(op.f('ix_event_applications_id'), table_name='event_applications')
    op.drop_index(op.f('ix_event_applications_event_id'), table_name='event_applications')
    op.drop_index(op.f('ix_event_applications_band_id'), table_name='event_applications')
    op.drop_index(op.f('ix_event_applications_applied_at'), table_name='event_applications')
    op.drop_table('event_applications')
    op.drop_index(op.f('ix_band_member_availabilities_id'), table_name='band_member_availabilities')
    op.drop_index(op.f('ix_band_member_availabilities_date'), table_name='band_member_availabilities')
    op.drop_index(op.f('ix_band_member_availabilities_band_member_id'), table_name='band_member_availabilities')
    op.drop_table('band_member_availabilities')
    op.drop_index(op.f('ix_band_events_status'), table_name='band_events')
    op.drop_index(op.f('ix_band_events_id'), table_name='band_events')
    op.drop_index(op.f('ix_band_events_event_id'), table_name='band_events')
    op.drop_index(op.f('ix_band_events_band_id'), table_name='band_events')
    op.drop_table('band_events')
    op.drop_index(op.f('ix_venue_staff_id'), table_name='venue_staff')
    op.drop_table('venue_staff')
    op.drop_index(op.f('ix_venue_operating_hours_venue_id'), table_name='venue_operating_hours')
    op.drop_index(op.f('ix_venue_operating_hours_id'), table_name='venue_operating_hours')
    op.drop_index(op.f('ix_venue_operating_hours_day_of_week'), table_name='venue_operating_hours')
    op.drop_table('venue_operating_hours')
    op.drop_index(op.f('ix_venue_availabilities_venue_id'), table_name='venue_availabilities')
    op.drop_index(op.f('ix_venue_availabilities_id'), table_name='venue_availabilities')
    op.drop_index(op.f('ix_venue_availabilities_date'), table_name='venue_availabilities')
    op.drop_table('venue_availabilities')
    op.drop_index(op.f('ix_events_venue_id'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_date'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_band_members_id'), table_name='band_members')
    op.drop_table('band_members')
    op.drop_index(op.f('ix_venues_name'), table_name='venues')
    op.drop_index(op.f('ix_venues_invite_code'), table_name='venues')
    op.drop_index(op.f('ix_venues_id'), table_name='venues')
    op.drop_index(op.f('ix_venues_city'), table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_bands_name'), table_name='bands')
    op.drop_index(op.f('ix_bands_invite_code'), table_name='bands')
    op.drop_index(op.f('ix_bands_id'), table_name='bands')
    op.drop_table('bands')
    # ### end Alembic commands ###
